# Generated by Django 4.1 on 2022-10-10 15:03

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighbourNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_pdf', models.FileField(null=True, upload_to=core.models.user_directory_path)),
                ('rc_pdf_old', models.FileField(null=True, upload_to=core.models.user_directory_path)),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrudList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kad_nr', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('name_address', models.CharField(max_length=200)),
                ('gim_data', models.CharField(max_length=20)),
                ('coordinates', models.CharField(max_length=20)),
                ('kad_address', models.CharField(max_length=200)),
                ('mat_date', models.CharField(max_length=20)),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRUD_1',
            },
        ),
    ]
