# Generated by Django 4.1 on 2022-10-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudlist',
            name='coordinates',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='crudlist',
            name='gim_data',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='crudlist',
            name='mat_date',
            field=models.CharField(max_length=200),
        ),
    ]
