# Generated by Django 4.1 on 2022-10-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_crudlist_coordinates_alter_crudlist_gim_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudlist',
            name='kad_address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='crudlist',
            name='name_address',
            field=models.CharField(max_length=500),
        ),
    ]
