# Generated by Django 4.1 on 2022-10-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_crudlist_kad_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudlist',
            name='kad_nr',
            field=models.CharField(max_length=200),
        ),
    ]
